[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_anchor_sveltekit_skeleton_starter = "7j6ARQdmgrJwEqgJDHC82nvwQX26qcDF79osU6M7kmui"

[programs.devnet]
solana_anchor_sveltekit_skeleton_starter = "7j6ARQdmgrJwEqgJDHC82nvwQX26qcDF79osU6M7kmui"

[registry]
url = "https://api.apr.dev"

[workspace]
types = "app/src/lib/idl/"  # Will copy IDL to frontend app as TS (not JSON!)

[provider]
cluster = "devnet" #"http://localhost:8899" #"localnet" #"devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
